# Generated by Django 5.1.3 on 2025-02-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
    ]
